export const MOVIE_FETCH_REQUEST = "MOVIE_FETCH_REQUEST"
export const MOVIE_FETCH_SUCCESS = "MOVIE_FETCH_SUCCESS"
export const MOVIE_FETCH_FAIL = "MOVIE_FETCH_FAIL"

export const MOVIES_FETCH_REQUEST = "MOVIES_FETCH_REQUEST"
export const MOVIES_FETCH_SUCCESS = "MOVIES_FETCH_SUCCESS"
export const MOVIES_FETCH_FAIL = "MOVIES_FETCH_FAIL"
export const MOVIES_FETCH_RESET = "MOVIES_FETCH_RESET"

export const MOVIES_REF_FETCH_REQUEST = "MOVIES_REF_FETCH_REQUEST"
export const MOVIES_REF_FETCH_SUCCESS = "MOVIES_REF_FETCH_SUCCESS"
export const MOVIES_REF_FETCH_FAIL = "MOVIES_REF_FETCH_FAIL"

export const MOVIES_SORT_REQUEST = "MOVIES_SORT_REQUEST"
export const MOVIES_SORT_SUCCESS = "MOVIES_SORT_SUCCESS"
export const MOVIES_SORT_FAIL = "MOVIES_SORT_FAIL"

export const MOVIES_MOST_POPULAR_REQUEST = "MOVIES_MOST_POPULAR_REQUEST"
export const MOVIES_MOST_POPULAR_SUCCESS = "MOVIES_MOST_POPULAR_SUCCESS"
export const MOVIES_MOST_POPULAR_FAIL = "MOVIES_MOST_POPULAR_FAIL"