export const PERSONS_FETCH_REQUEST = "PERSONS_FETCH_REQUEST"
export const PERSONS_FETCH_SUCCESS = "PERSONS_FETCH_SUCCESS"
export const PERSONS_FETCH_FAIL = "PERSONS_FETCH_FAIL"

export const PERSON_FETCH_REQUEST = "PERSON_FETCH_REQUEST"
export const PERSON_FETCH_SUCCESS = "PERSON_FETCH_SUCCESS"
export const PERSON_FETCH_FAIL = "PERSON_FETCH_FAIL"

export const PERSONS_COUNT = "PERSONS_COUNT"